### ISSUE TITLE
Preprocessing and extension method

### ISSUE THREAD

**Issue by dzambrano** [ox-vgg/vgg_face2#10]
Hi, I'd like to ask about the extension method you used.

In the provided [Matlab code](https://github.com/ox-vgg/vgg_face2/blob/9f3784518135bc594cef3c52e0bbd0ebbe0dc103/standard_evaluation/demo_proj.m#L77), the bounding box is extended by a factor of 0.3 starting from the center. This approach should be similar to what has been used during training with the VGGFace2 dataset. In the Pre-processing section, is has been claimed that the original faces are obtained with an extension factor of 1.0. However, if I extend the bounding box of any image from the VGGFace2 dataset by a factor of 1.0, I do not obtain the original image. 
According to the already mentioned Matlab code, there is also a ```scal_ratio_min``` to consider, which has an arbitrary value of 112/128. However, by considering it, the obtained image size is larger than the provided face. 

Is there anything I'm missing? How did you crop the original images? and how it should be implemented the extension method? 
Thanks!

**Comment by WeidiXie** [comment]
@dzambrano 
Hi, 

The VGGFace2 dataset we provide now is a loose crop of the detection, that's not the version we used for training our model,

we also provide the bounding box here: http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/meta_infor.html

by using these boundingbox, you should be able to get the tight crop faced.

Best
Weidi

**Comment by dzambrano** [comment]
Thanks for the reply.
Then, for training, do you extend the bounding boxes as in here:
```tight_bb_w_h = bb_size(2) * [scal_ratio, 1] * (1 + det_tight_ratio);``` ?

**Comment by WeidiXie** [comment]
@dzambrano 

I think the code is right,

I put some sample images in the repo, could you check them, and see if you still have problems in getting the tightly cropped faces?

Best
Weidi

**Comment by dzambrano** [comment]
Hi,
Thanks for the sample images, they were very useful. 
I've made some tests with the code I wrote before, and I got slightly different results. 

Here some examples, one for each subject you provided:
```
n000106/0003_01.jpg
loose_crop (369, 354)
my_crop   (236, 206)
tight_crop (263, 230)
```
``` 
n007241/0005_01.jpg
loose_crop  (317, 277)
my_crop     (216, 188)
tight_crop   (206, 181)
```
```
n008937/0003_01.jpg
loose_crop (535, 522)
my_crop    (394, 344)
tight_crop  (413, 362)
```
where ```loose_crop``` and ```tight_crop``` are the sizes of the images you provided.
It could be an approximation error due to some rounding. 
However, in a few cases the difference is quite large. 
Any idea?

**Comment by WeidiXie** [comment]
@dzambrano 

I think as long as your crop is close to the provided tight_crop, the model won't have too much problem.

Worst case would be, you can do your own crop, and finetune the model for one or two epochs.

Best
Weidi

**Comment by dzambrano** [comment]
Right, thanks, indeed the model doesn't seem very different. 

However, I only have the loose_corp (the actual released images) thus I cannot finetune the model on the tight_corps. 

Best,
Davide

**Comment by WeidiXie** [comment]
@dzambrano  

Well, just find a face detector and run it on our loosely cropped images, and define your own crop strategy, then finetune our model on your crops.

When deploying the model, as long as you use the same crop (you defined yourself) for testing, the model is good to go.

Best
Weidi
