### ISSUE TITLE
About the released loose_bb_test.csv

### ISSUE THREAD

**Issue by kerenfu** [ox-vgg/vgg_face2#12]
Thank you for sharing the work. Great! I would like to ask about the released meta data, exactly the loose_bb_test.cvs and loose_bb_train.csv. It is a bit confusion about the description "loose" for them. 
Do they contain face bounding boxes of the original MTCNN detector, or they contain the extended bounding boxes by factor 0.3 as described in the paper. 
Thanks!

**Comment by WeidiXie** [comment]
I have uploaded some sample images, it includes the released crop and the tight crop (extend 0.3) we used to train our model, please check them.

Best
Weidi
