### ISSUE TITLE
when i  ues your method,there is a probelm ,

### ISSUE THREAD

**Issue by seriousran** [ox-vgg/vgg_face2#15]
when i  ues your method,there is a probelm ,
self.conv1_7x7_s2 = self.__conv(2, name='conv1/7x7_s2', in_channels=3, out_channels=64, kernel_size=(7L,7L), stride=(2L,2L), groups=1, bias=False)
                                                                                                          ^
SyntaxError: invalid syntax

could you help me?  thank you very much

_Originally posted by @jilner in https://github.com/ox-vgg/vgg_face2/issues/5#issuecomment-448463242_

**Comment by seriousran** [comment]
I have a same problem! And then I made it as an opened issue.
(SE-ResNet-50-256D, pyTorch)
I think the problem is the '7L' in the kernel_size.

What does it mean, the 'L'?

**Comment by lishen-shirley** [comment]
The pytorch models were imported from Caffe via the tool "MMdnn" with python2, thus the prototxt was generalized by following the rules defined in the tool. 'L' indicates 'long' type in python2, and it's renamed to 'int' in python3. You can try to switch to python2.* or remove 'L'.

**Comment by jilner** [comment]
> I have a same problem! And then I made it as an opened issue.
> (SE-ResNet-50-256D, pyTorch)
> I think the problem is the '7L' in the kernel_size.
> 
> What does it mean, the 'L'?

it mean  long  in python2  ,you can  remove ，but  when load the mondel,there will be anthor question,the best way is to  use python2

**Comment by seriousran** [comment]
Thanks @lishen-shirley and @jilner !!
It was my fault because my jupyter lab was not well configured with python2.
I chose python2, however, it was working on python3.

I understood 'L' now, Thanks for ur kind reply.
