### ISSUE TITLE
Release date for TF model

### ISSUE THREAD

**Issue by Niklasaaron** [ox-vgg/vgg_face2#16]
Do you roughly know when the model for TF will be added?

**Comment by WeidiXie** [comment]
Currently, I have a Keras + TF model, is that OK ?

**Comment by Niklasaaron** [comment]
Keras would be perfect!

**Comment by WeidiXie** [comment]
Hey, @Niklasaaron 

Could you check this 
https://drive.google.com/file/d/1XkVoWvJXeiLHo_pkuPYp2c4LEg6npkiI/view?usp=sharing

This model is trained with a slightly different tight crops, but I have also tested on the tight crops (as we did in the paper), and am able to get similar results (on IJBB).

TAR @ FAR = 1e-05 : 0.64
TAR @ FAR = 0.0001 : 0.78
TAR @ FAR = 0.001 : 0.88
TAR @ FAR = 0.01 : 0.94
TAR @ FAR = 0.1 : 0.98

Meaning, it should be pretty robust to the tightly cropped faces of different strategies.

Best
Weidi

**Comment by Niklasaaron** [comment]
Thank you so much this is really helpful!

best, Niklas
