### ISSUE TITLE
How to use the testset of VGGFACE2

### ISSUE THREAD

**Issue by qjfytz** [ox-vgg/vgg_face2#19]
I'm a little confused that It seems there is no standard usage of the test set. In the article, the author present the result on cross-age and cross-pose evaluation using the test set. However, I haven't found any instruction shows how to format the comparison pairs and how to test. There is no benchmark on the test set.
In this repository, I found the evaluation is performed on IJB dataset, so we are not encouraged to use the test set vggface2 offered for evaluation? and why?

**Comment by WeidiXie** [comment]
@qjfytz 
Hi, 

As IJB benchmarks are challenging and publicly available, so we encourage users to test on IJB benchmarks.

Best
Weidi
