### ISSUE TITLE
Resumable link to VGGFace2 dataset.

### ISSUE THREAD

**Issue by Sawatdatta** [ox-vgg/vgg_face2#20]
Hello Author, is it possible for you to share the database if you have downloaded it at your end. please share via Dropbox or any other method. I am not able to completely download the database from original location, the download stops due to network or power interruption and cannot be resumed. I have tried plenty of times.

If you have it downloaded please share the link.

Thank in advance.

**Comment by nblauch** [comment]
i am not an author but i did download it recently. you may need to find a better internet connection.

**Comment by WeidiXie** [comment]
Hi, 

You may find this useful:
https://www.dropbox.com/sh/dml593thvs0vfr1/AAAzPS2DBQZ5uLfSo5wlI_JZa?dl=0

Best,
Weidi

**Comment by Sawatdatta** [comment]
Thanks a lot.

**Comment by aseembits93** [comment]
Thank you for sharing the link @WeidiXie :) It's very helpful. I just wanted to know how I can combine the different subfolders of the training set (_aa, _ab and so on) after download? The files for the training set do not have any extension.
Thank you again for sharing the dataset!

**Comment by yaelfregier** [comment]
Hi @WeidiXie ,

I have tried to access VGGFace2 via the official link, but it is broken. Then Google brought me to this thread, but the dropbox file has been deleted. Is there another way to access the dataset?

Thanks in advance!

Yaël.
