### ISSUE TITLE
Questions about finetune settings

### ISSUE THREAD

**Issue by Steve-Tod** [ox-vgg/vgg_face2#21]
Hi,
When you are preprocessing the images for fine-tuning, do you align the faces with key points detected by MTCNN and then crop them? Or you just resize and random/center crop them？

**Comment by WeidiXie** [comment]
Hi, @Steve-Tod 
We train the model without alignment, but since you want to fine-tune the model on your data, you can align them first. As long as your training and testing process is consistent, meaning you also test the model with alignment.

**Comment by Steve-Tod** [comment]
Thank you! 
I've downloaded a pre-trained model on aligned MS1M. I want to fine-tune it with vgg face2 and test it on IJB-A. However, since there are faces with big angles so I can't align it. 
So would it matter if I fine-tune the pre-trained model(trained on aligned MS1M) with vgg face2(not aligned to be consistent with test)?

**Comment by WeidiXie** [comment]
It should be fine, just make sure you use the same crop when finetuning on the VGGFace2 and IJB-A, IJB-B, IJB-C.

**Comment by Steve-Tod** [comment]
Thank you so much for your response!
