### ISSUE TITLE
About the  balacing-sampling strategy?

### ISSUE THREAD

**Issue by acnazarejr** [ox-vgg/vgg_face2#24]
Hi, in the paper (page 4, in section Training Implementation Details) it is mentioned: **..., with a balancing-sampling strategy for each mini-batch due to the unbalanced training distributions...**. Could you give more details regarding this strategy?

**Comment by WeidiXie** [comment]
Hi, 

this is just to make sure each mini-batch must contain samples from different identities.
In the dataset, the average number of images for one identity can be >360, and we don't want to sample a mini-batch (256 images) all with same identities.


Best,
Weidi

**Comment by acnazarejr** [comment]
Ok, thank you!

**Comment by vvigilante** [comment]
May I ask how to the authors how the strategy works exactly?
Is shuffling the dataset not enough?

Thank you for your kind answer!
Vincenzo.
