### ISSUE TITLE
Links for downloading are not working

### ISSUE THREAD

**Issue by pabloapast** [ox-vgg/vgg_face2#27]
Hi,

I want to download the dataset but I'm receiving the following error message:
```
Not Found
The requested URL /vgg_face2/get_file was not found on this server.
```
Do you know what's happening?

**Comment by WeidiXie** [comment]
Hi, @pabloapast 

It should be fixed now.

Best,
Weidi

**Comment by pabloapast** [comment]
Working now! Thanks
