### ISSUE TITLE
Images Normalization

### ISSUE THREAD

**Issue by wfcb-85** [ox-vgg/vgg_face2#29]
Hello,  
My question is mostly theoric : You mentioned in another issue that your normalization steps include only the mean substraction from each channel of each image. However, according to some people, e.g., http://josh-tobin.com/assets/pdf/troubleshooting-deep-neural-networks-01-19.pdf, not having input values between 0 and 1 could hurt performance. So my question is why are your input values much bigger than 1. Thanks in advance.

**Comment by WeidiXie** [comment]
Hi, That's usually not a problem in computer vision now, since you have batch norm layers.
