### ISSUE TITLE
New models Matconvnet links are not working

### ISSUE THREAD

**Issue by panegri** [ox-vgg/vgg_face2#3]
Hi,
As the title said, the links of the new Matconvnet models are not working.
Best regards,
Pablo

**Comment by WeidiXie** [comment]
Hi, Pablo

Could you be more specific ? which link of the MatconvNet model is not working ?

Best
Weidi

**Comment by panegri** [comment]
Hi Weidi,
I got the following error resnet50_256:

The webpage at http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/models/matconvnet/resnet50_256_mat.tar.gz might be temporarily down or it may have moved permanently to a new web address.
ERR_CONTENT_DECODING_FAILED

The same happens with the other new models:

matconvnet/senet50_128_mat.tar.gz
matconvnet/senet50_256_mat.tar.gz
matconvnet/resnet50_128_mat.tar.gz

Best,

Pablo

**Comment by lishen-shirley** [comment]
Hi Pablo,

The matconvnet modes are being evaluated and will be accessible today. I'll let you know when they are ready to download. 

Thank you.

**Comment by lishen-shirley** [comment]
The matconvnet models are accessible now.

**Comment by panegri** [comment]
Thanks!!!
