### ISSUE TITLE
Different protocol

### ISSUE THREAD

**Issue by cassie101** [ox-vgg/vgg_face2#30]
Hi @WeidiXie, may I check with you if you have the ijbb_face_tid_mid.txt and ijbb_template_pair_label.txt for covariate protocol? 
I am trying to map the template to image but realized that your images are named differently from original sources, thus I'm unable to proceed using your loose crop images.

**Comment by WeidiXie** [comment]
Hi, I would recommend you to go the original IJBB dataset, because my list is a bit different ....

**Comment by jlamperez** [comment]
Hi @WeidiXie, 

Can you tell me how did you create *ijbb_face_tid_mid.txt* file?

**Comment by jlamperez** [comment]
Okey I have seen that I need to create *ijbb_face_tid_mid* using *ijbb_1N_gallery_S1, ijbb_1N_gallery_S2, ijbb_1N_probe_mixed*.

**Comment by WeidiXie** [comment]
Hi, @jlamperez 
Well, the images have been changed to different names while we saving them, so I guess it's a bit difficult to recover from the standard NIST dataset.

But you can use the standard IJB dataset provided by NIST.
