### ISSUE TITLE
How to compute embedding for SENET50 model

### ISSUE THREAD

**Issue by happypanda5** [ox-vgg/vgg_face2#31]
Hello, I am unable to compute embedding for SENET50_128 dim model.

I have loaded the model as follows

`# senet50_128_pytorch is the model name
import os,  imp, torch
os.chdir("/content/senet50_128_pytorch")
MainModel = imp.load_source("MainModel", "senet50_128_pytorch.py") 
model = torch.load('senet50_128_pytorch.pth')`

I then supply it an image of dims 224x224x3 as a numpy array, and use 

`face_feats = model.feat_extract( sample_image )`

to extract 128 dimensional embedding, but I get the following error

> AttributeError: 'Conv2d' object has no attribute 'padding_mode'

Can you please help. Thanks

**Comment by WeidiXie** [comment]
Hi, could you try again, the pytorch models have been updated.
