### ISSUE TITLE
VGGFace2 Download Unavailable

### ISSUE THREAD

**Issue by BAI-Yeqi** [ox-vgg/vgg_face2#34]
When I was trying to download VGGFace2 with the provided link: 
http://zeus.robots.ox.ac.uk/vgg_face2/get_file?fname=vggface2_train.tar.gz

The website shows:
Not Found
The requested URL /vgg_face2/get_file was not found on this server.

**Comment by WeidiXie** [comment]
Hi, @BAI-Yeqi 
It should be OK now.

**Comment by AndrewWang996** [comment]
Seems to be broken again @WeidiXie
