### ISSUE TITLE
Use pretrained model and convert to tfjs

### ISSUE THREAD

**Issue by msvargas** [ox-vgg/vgg_face2#36]
Hi, VGG-Face2 is amazing, but
Could you convert models to tensorflowjs using torch models without any problem?
Could you use your pretrained models without any problem?
Sorry, I don't know much about licensing in models and datasets, I currently have a facial recognition implemented with dlib but I want more robust
Thank you

**Comment by WeidiXie** [comment]
Hi,
Sorry I don't  know how to use the tensorflowJS.

**Comment by msvargas** [comment]
> Hi,
> Sorry I don't know how to use the tensorflowJS.

Thanks, i convert to tensorflow.js using pytorch2keras package, 

weights tfjs VGGFace2: https://drive.google.com/drive/folders/1oRiz4GcVmJA0L1atfXOAi4jFEUYwv8iU?usp=sharing

example code:

```js
const path = require("path");
const tf = require("@tensorflow/tfjs-node");
const fs = require("fs");
const similarity = require("compute-cosine-similarity");

const BASE_DIR =  "./";
var vggFace2Model;
// siamese networks : https://towardsdatascience.com/one-shot-learning-with-siamese-networks-using-keras-17f34e75bb3d
async function run() {
  console.time("load model");
  const model = await tf.loadLayersModel(
    `file://${path.resolve(__dirname, "weights-v2", "model.json")}`
  );
  console.timeEnd("load model");
  //const prediction  = model.predict(tf.randomNormal([1, 3, 224, 224])) ;
  console.time("prediction");
  vggFace2Model = tf.model({
    inputs: model.layers[0].input,
    outputs: model.layers.slice(-3)[0].output
  });
  const prediction = vggFace2Model.predict(preprocessImage("./images/11.jpg"));
  prediction.print();
  console.timeEnd("prediction");
  console.log(prediction);
}

function preprocessImage(imagePath) {
  const image = tf
    .expandDims(
      tf.image.resizeNearestNeighbor(
        tf.node.decodeJpeg(new Uint8Array(fs.readFileSync(imagePath))),
        [224, 224],
        true
      ),
      0
    )
    .reshape([1, 3, 224, 224]);
  //image.shape[0] = null
  return image;
}
const epsilon = 0.25;
function findCosineSimilarity(labels, predictions) {
  const a = tf.matMul(labels, predictions, true, false);
  const b = tf.sum(...tf.square(labels).dataSync());
  const c = tf.sum(...tf.square(predictions).dataSync());
  const res = tf.div(a, tf.mul(tf.sqrt(b), tf.sqrt(c)));
  res.print();
  return 1.0 - res.dataSync();
}
async function verifyFace(img1, img2) {
  const img1_descriptors = vggFace2Model.predict(
    preprocessImage(path.resolve(BASE_DIR, img1))
  );
  const img2_descriptors = vggFace2Model.predict(
    preprocessImage(path.resolve(BASE_DIR, img2))
  );
  /* console.log(
    findCosineSimilarity(img1_descriptors,img2_descriptors)
  ); */
  const distance =
    1.0 -
    similarity(
      Array.from(img1_descriptors.dataSync()),
      Array.from(img2_descriptors.dataSync())
    );
  //distance.print();
  console.log(distance);
  if (distance < epsilon) {
    console.log("verified... they are same person");
  } else {
    console.log("unverified! they are not same person!");
  }
}
run();
```
i hope help to anybody
:)

**Comment by mdiedov** [comment]
> > Hi,
> > Sorry I don't know how to use the tensorflowJS.
> 
> Thanks, i convert to tensorflow.js using pytorch2keras package,
> 
> weights tfjs VGGFace2: https://drive.google.com/drive/folders/1oRiz4GcVmJA0L1atfXOAi4jFEUYwv8iU?usp=sharing
> 
> example code:
> 
> ```js
> const path = require("path");
> const tf = require("@tensorflow/tfjs-node");
> const fs = require("fs");
> const similarity = require("compute-cosine-similarity");
> 
> const BASE_DIR =  "./";
> var vggFace2Model;
> // siamese networks : https://towardsdatascience.com/one-shot-learning-with-siamese-networks-using-keras-17f34e75bb3d
> async function run() {
>   console.time("load model");
>   const model = await tf.loadLayersModel(
>     `file://${path.resolve(__dirname, "weights-v2", "model.json")}`
>   );
>   console.timeEnd("load model");
>   //const prediction  = model.predict(tf.randomNormal([1, 3, 224, 224])) ;
>   console.time("prediction");
>   vggFace2Model = tf.model({
>     inputs: model.layers[0].input,
>     outputs: model.layers.slice(-3)[0].output
>   });
>   const prediction = vggFace2Model.predict(preprocessImage("./images/11.jpg"));
>   prediction.print();
>   console.timeEnd("prediction");
>   console.log(prediction);
> }
> 
> function preprocessImage(imagePath) {
>   const image = tf
>     .expandDims(
>       tf.image.resizeNearestNeighbor(
>         tf.node.decodeJpeg(new Uint8Array(fs.readFileSync(imagePath))),
>         [224, 224],
>         true
>       ),
>       0
>     )
>     .reshape([1, 3, 224, 224]);
>   //image.shape[0] = null
>   return image;
> }
> const epsilon = 0.25;
> function findCosineSimilarity(labels, predictions) {
>   const a = tf.matMul(labels, predictions, true, false);
>   const b = tf.sum(...tf.square(labels).dataSync());
>   const c = tf.sum(...tf.square(predictions).dataSync());
>   const res = tf.div(a, tf.mul(tf.sqrt(b), tf.sqrt(c)));
>   res.print();
>   return 1.0 - res.dataSync();
> }
> async function verifyFace(img1, img2) {
>   const img1_descriptors = vggFace2Model.predict(
>     preprocessImage(path.resolve(BASE_DIR, img1))
>   );
>   const img2_descriptors = vggFace2Model.predict(
>     preprocessImage(path.resolve(BASE_DIR, img2))
>   );
>   /* console.log(
>     findCosineSimilarity(img1_descriptors,img2_descriptors)
>   ); */
>   const distance =
>     1.0 -
>     similarity(
>       Array.from(img1_descriptors.dataSync()),
>       Array.from(img2_descriptors.dataSync())
>     );
>   //distance.print();
>   console.log(distance);
>   if (distance < epsilon) {
>     console.log("verified... they are same person");
>   } else {
>     console.log("unverified! they are not same person!");
>   }
> }
> run();
> ```
> 
> i hope help to anybody
> :)

can you repost link to google drive?
