### ISSUE TITLE
VGGFace2 Download Issue

### ISSUE THREAD

**Issue by ghost** [ox-vgg/vgg_face2#37]
Hello, 

When trying to login and download the VGGFace2 dataset at http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/, I am greeted with a 'FORTINET Firewall Notification' that reads: 
"Your access has been blocked by firewall policy 10263.
If you have any further concerns, please contact your network administrator for more information."

When trying to `wget` from a Google Colab instance I experience the same issue. Is there any alternative host that I can download the dataset from.

Many thanks

**Comment by WeidiXie** [comment]
Fixed
