### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by NeHo4y** [ox-vgg/vgg_face2#38]
Seems like download link http://zeus.robots.ox.ac.uk/vgg_face2/get_file?fname=vggface2_test.tar.gz not working again. (as well as train set).

Returns:
Not Found
The requested URL /vgg_face2/get_file was not found on this server.

**Comment by WeidiXie** [comment]
This has been fixed.

**Comment by gdahia** [comment]
Greetings.

I believe this problem is happening again.

**Comment by WeidiXie** [comment]
@gdahia 
Can you try again ?

**Comment by gdahia** [comment]
It worked now. Thanks :)
