### ISSUE TITLE
Links for downloading are not working

### ISSUE THREAD

**Issue by Honzys** [ox-vgg/vgg_face2#4]
Hello,

firstly I want to thank you for your work!

But when I try to download the dataset (I am logged in) website shows:

    Not Found

    The requested URL /vgg_face2/get_file was not found on this server.

It is possible that I don't have access? Or is it a problem on your side with the files?

Thank you very much!

**Comment by ox-vgg** [comment]
The links are back to work. Please try again. Thank you for reporting the issue.

**Comment by fushuhao6** [comment]
Hi, I got the same issue today.

The requested URL /vgg_face2/get_file was not found on this server.

Could you check again?

Thank you!

**Comment by WeidiXie** [comment]
hi, @howardmumu 

It should be fixed now.

Best,
Weidi
