### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by ryokamoi** [ox-vgg/vgg_face2#40]
Download links for train and test data at [https://www.robots.ox.ac.uk/~vgg/data/vgg_face2/data_infor.html](https://www.robots.ox.ac.uk/~vgg/data/vgg_face2/data_infor.html) are not working.

They return:
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

I've received this message for the last few days.

**Comment by ecoto** [comment]
@ryokamoi please try again

**Comment by ryokamoi** [comment]
It works now. Thank you very much.
