### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by ceoluo** [ox-vgg/vgg_face2#43]
Download links for train and test data at https://www.robots.ox.ac.uk/~vgg/data/vgg_face2/data_infor.html are not working.

They return:
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by WeidiXie** [comment]
Hi, Can you try again ?

**Comment by ceoluo** [comment]
It works now, thanks!
