### ISSUE TITLE
PyTorch model loading

### ISSUE THREAD

**Issue by makarandtapaswi** [ox-vgg/vgg_face2#5]
Hi,

I was trying to load the models in PyTorch and it didn't seem obvious since `np.load()` on the weights file just gives a single integer. Anyway, after some searching I was able to find https://github.com/Microsoft/MMdnn/issues/378#issuecomment-416161818 that informs how to use the loader, and this works for me now. Can this be included in the tarball, or the README on this to help future users?

```python
import imp
import torch

MainModel = imp.load_source('MainModel', 'senet50_256_pytorch.py')
model = torch.load('senet50_256_pytorch.pth')
random_feat = model(torch.randn(1, 3, 224, 224))
print(random_feat.squeeze().size())
```

Thanks!

**Comment by WeidiXie** [comment]
Hi, 

Thanks for the suggestion, will do that.

Best
Weidi

**Comment by kaiwang960112** [comment]
> Hi,
> 
> I was trying to load the models in PyTorch and it didn't seem obvious since `np.load()` on the weights file just gives a single integer. Anyway, after some searching I was able to find [Microsoft/MMdnn#378 (comment)](https://github.com/Microsoft/MMdnn/issues/378#issuecomment-416161818) that informs how to use the loader, and this works for me now. Can this be included in the tarball, or the README on this to help future users?
> 
> ```python
> import imp
> import torch
> 
> MainModel = imp.load_source('MainModel', 'senet50_256_pytorch.py')
> model = torch.load('senet50_256_pytorch.pth')
> random_feat = model(torch.randn(1, 3, 224, 224))
> print(random_feat.squeeze().size())
> ```
> 
> Thanks!

could you tell me how to use weight_file？ I use your method, 
![image](https://user-images.githubusercontent.com/37533040/47408212-f1652400-d790-11e8-8468-a915612bce50.png)
and then I got TypeError: 'KitModel' object has no attribute '__getitem__'

**Comment by makarandtapaswi** [comment]
You should do exactly what I have written in the code. If you are using `__init__()` under a `nn.Module`, that is not required. Similarly, the `super()` is not required. When you run `model = torch.load()` from my comment above that actually loads all the weights and gives you a model object that you can pass a batch of face images to directly. I have used a random feature input just to see that it works.

**Comment by jilner** [comment]
when i  ues your method,there is a probelm ,
self.conv1_7x7_s2 = self.__conv(2, name='conv1/7x7_s2', in_channels=3, out_channels=64, kernel_size=(7L,7L), stride=(2L,2L), groups=1, bias=False)
                                                                                                          ^
SyntaxError: invalid syntax

could you help me?  thank you very much
