### ISSUE TITLE
Website gives 404 error

### ISSUE THREAD

**Issue by bjoernpl** [ox-vgg/vgg_face2#50]
The VGGFace2 Website ( http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/ ) is not available and hasn't been for a few days. It only reports a 404 error with the message `The requested URL was not found on this server.` Any info on this?

**Comment by hardik-uppal** [comment]
I also have been trying for a few days now. Same issue!

**Comment by deaffella** [comment]
Same issue! Please give us a valid download url

**Comment by WeidiXie** [comment]
Hi, 
Thanks for your interest, I'm afraid the dataset will remain offline for now.

**Comment by luisfmnunes** [comment]
> Hi,
> Thanks for your interest, I'm afraid the dataset will remain offline for now.

Thanks for the info.
Hope the dataset become available once again soon

**Comment by ivanlen** [comment]
I am having the same issue. it is a pity that the dataset is not online anymore 💔 .
Do you have an estimate of when it is going to be online again?

**Comment by aviallon** [comment]
Does someone have a copy of the tar.gz laying around for share?

**Comment by ysarathy99** [comment]
see https://github.com/ox-vgg/vgg_face2/issues/2

**Comment by adamhrv** [comment]
Hi @WeidiXie, was the dataset removed for legal reasons by the university? Your earlier response mentioned "I'm afraid we won't able to put the dataset online until the University Legal team agrees." Does this mean there could be potential legal issues using the dataset, and or using it for models? Any updates on legal status much appreciated.
