### ISSUE TITLE
IJBC meta file ?

### ISSUE THREAD

**Issue by Edwardmark** [ox-vgg/vgg_face2#53]
Hi, could you please provide the ijbc meta file like the ijbb meta file? @WeidiXie  Thanks.
https://github.com/deepinsight/insightface/issues/556
As the issue says, it uses your meta file, but I could not find it. Could you kindly please provide me the meta file of ijbc?

**Comment by whkwls2653** [comment]
> Hi, could you please provide the ijbc meta file like the ijbb meta file? @WeidiXie Thanks.
> [deepinsight/insightface#556](https://github.com/deepinsight/insightface/issues/556)
> As the issue says, it uses your meta file, but I could not find it. Could you kindly please provide me the meta file of ijbc?

You can find meta file of ijbc at insight face gihub.  https://github.com/deepinsight/insightface/tree/master/evaluation/IJB

**Comment by Edwardmark** [comment]
> > Hi, could you please provide the ijbc meta file like the ijbb meta file? @WeidiXie Thanks.
> > [deepinsight/insightface#556](https://github.com/deepinsight/insightface/issues/556)
> > As the issue says, it uses your meta file, but I could not find it. Could you kindly please provide me the meta file of ijbc?
> 
> You can find meta file of ijbc at insight face gihub. https://github.com/deepinsight/insightface/tree/master/evaluation/IJB

Thanks.
