### ISSUE TITLE
Input image dimension

### ISSUE THREAD

**Issue by mohammad7t** [ox-vgg/vgg_face2#6]
Hi,

Thanks for the great work. What is the required dimension for input images? I have tried some square-images and each of them raises a different tensor size mismatch exception.

**Comment by lishen-shirley** [comment]
The input spatial dimensions are 224x224. If you want to use a different size, you might try to change the kernel size in global-average pooling layer. The stages used in the architectures follow the definition in the ResNet paper.

**Comment by mohammad7t** [comment]
Thanks!
