### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by alpercalisir** [ox-vgg/vgg_face2#7]
Currently I face a download error. Is there any specific reason for this ?

**Comment by WeidiXie** [comment]
Hi, 

Could you give a more detailed description about the problem ? 
Do you have problem in downloading the model or dataset? which model exactly ? @calisir

Thanks
Best
Weidi

**Comment by alpercalisir** [comment]
@WeidiXie Sorry for not being clear.

The problem I encountered is happening when I try to download _Train Data_v1_ 
The link I try to download:
http://zeus.robots.ox.ac.uk/vgg_face2/get_file?fname=vggface2_train.tar.gz

**Comment by WeidiXie** [comment]
@calisir  It should be fixed now.

Sorry for the inconvenience.

Best
Weidi

**Comment by alpercalisir** [comment]
Seems to be solved.

Thanks
