### ISSUE TITLE
I can't download "Train Data_v1" and "Test Data_v1"

### ISSUE THREAD

**Issue by zhaojinxi** [ox-vgg/vgg_face2#8]
Please help. I tried all the methods and the download link still shows 502 Bad Gateway.
The only problem files are "Train Data_v1" and "Test Data_v1". Other files do not have this problem. The login and registration in the upper right corner of the page also displays 502.

**Comment by zhaojinxi** [comment]
I can't download it in China. I use vpn, Japan and the US ip can't download files and register too.

**Comment by zhaojinxi** [comment]
I tried chrome, ie, edge, I can't download it, and I can't register and log in. I can't download it with various download software.

**Comment by WeidiXie** [comment]
Hi,  

@zhaojinxi It should be fixed now.

Sorry for the inconvenience.

Best
Weidi
