### ISSUE TITLE
About python version

### ISSUE THREAD

**Issue by xmq1221** [ox-vgg/vgg_face2#9]
I was trying to load the pretrained model, but I encountered the error
`/home/disk3/xmq/anaconda3/lib/python3.6/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'MainModel.KitModel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/home/disk3/xmq/data/code/pytorch/resnet_modify/models/VGGFace2-pytorch/models/resnet50_scratch_pytorch/test_weights.py", line 10, in <module>
    model = torch.load('resnet50_scratch_pytorch.pth')
  File "/home/disk3/xmq/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/disk3/xmq/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1124: ordinal not in range(128)`

After searching I found that I used python3 to load your pretrained model, and solved it.
So could you please write your python version in the readme file, and others won't have the same problem?

**Comment by WeidiXie** [comment]
@xmq1221   Thanks for the suggestion, I have added that in the README.

Best
Weidi

**Comment by xmq1221** [comment]
> @xmq1221 Thanks for the suggestion, I have added that in the README.
> 
> Best
> Weidi

That helps a lot

**Comment by pbehjatii** [comment]
Hi @xmq1221. I have the same problem and im using python3. Could u please tell how did you solve the problem?
